# Generated by Django 2.2.16 on 2020-09-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
